# Generated by Django 3.1.2 on 2020-10-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201019_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='aproved_comment',
            field=models.BooleanField(default=False),
        ),
    ]
